# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.2
	loader_version=0.19.3

# FMJ deps
	loader_dependency = >=0.18.0
	minecraft_dependency = ~26.2
	carpet_dependency = ~26.2

# Mod Properties
	mod_version = 0.6.1
	maven_group = me.wavetech
	archives_base_name = wavecarpet

# Dev Dependencies
	loom_version = 1.17.17

# Dependencies
	carpet_version = 26.2+v260616
