# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=1.21.11
	loader_version=0.19.3

# FMJ deps
	loader_dependency = >=0.18.0
	minecraft_dependency = 1.21.11
	carpet_dependency = ~1.4

# Mod Properties
	mod_version = 0.6.1
	maven_group = me.wavetech
	archives_base_name = wavecarpet

# Dev Dependencies
	loom_version = 1.17.17

# Dependencies
	carpet_version = 1.21.11-1.4.194+v260107
	parchment_version = 1.21.11:2025.12.20
