# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=25w21a
	loader_version=0.16.14

# FMJ deps
	loader_dependency = >=0.16.0
	minecraft_dependency = >1.21.5
	carpet_dependency = ~1.4

# Mod Properties
	mod_version = 0.6.3
	maven_group = me.wavetech
	archives_base_name = wavecarpet

# Dependencies
	carpet_version = 25w20a-1.4.174+v250513
	parchment_version = 1.21.5:2025.04.19
